### ISSUE TITLE
I would like to run a minecraft server

### ISSUE THREAD

**Issue by zKowyth** [vital987/vubuntu#10]
Hi!
I would like to run a minecraft server, but the problem is the port as if idk it is closed :/

The server runs fine but I can't connect to it

(Minecraft servers use java)

Oh and also, how exactly how do I connect to it using VNSViewer?

**Comment by vital987** [comment]
* In case of Heroku, it only exposes one port that only allows HTTP/HTTPS requests so you cannot connect to Minecraft server & VNC ports directly via Heroku URL(Needs TCP), you have to do IP Tunneling (eg: ngrok) but it is slow so it may bring lag in your gaming. Their are readymade buildpacks available (uses IP tunneling) for Heroku rather than creating your own.
