### ISSUE TITLE
add google-chrome to the template

### ISSUE THREAD

**Issue by ignisc4t** [vital987/vubuntu#14]
hi, can you add chrome to the dockerfile purevnc branch  ?
I'm trying but I'm not that familiar with docker and look like it just doesn't work.

thanks

**Comment by vital987** [comment]
I chose brave browser as chrome alternative cause it dosen't have any google interference and is made from the same base by which google-chrome is made, so you get same, rather more features than chrome browser, also brave has tor inbuilt, but if still you want to install chrome then add the below code to the **Dockerfile.heroku** on new line:
```
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp && \
apt-get install --no-install-recommends -y /tmp/google-chrome-stable_current_amd64.deb && \
apt-get --fix-broken install -y
```
And redeploy it on Heroku.
[ * ] If you are deploying it on a non-heroku source then add the below code on line 131(replace text on line 131):
```
apt-get install -y powershell && \
#Google Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp && \
apt-get install --no-install-recommends -y /tmp/google-chrome-stable_current_amd64.deb && \
apt-get --fix-broken install -y
```
[ ! ] you need to launch google-chrome from the terminal cause google-chrome launcher isn't built in fluxbox menu.
Launch google chrome by running the below command in the terminal:
```google-chrome-stable --no-sandbox```
If your issue is resolved then close this issue.

**Comment by ignisc4t** [comment]
> I chose brave browser as chrome alternative cause it dosen't have any google interference and is made from the same base by which google-chrome is made, so you get same, rather more features than chrome browser, also brave has tor inbuilt, but if still you want to install chrome then add the below code to the **Dockerfile.heroku** on new line:
> 
> ```
> RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp && \
> apt-get install --no-install-recommends -y /tmp/google-chrome-stable_current_amd64.deb && \
> apt-get --fix-broken install -y
> ```
> 
> And redeploy it on Heroku.
> [ * ] If you are deploying it on a non-heroku source then add the below code on line 131(replace text on line 131):
> 
> ```
> apt-get install -y powershell && \
> #Google Chrome
> wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp && \
> apt-get install --no-install-recommends -y /tmp/google-chrome-stable_current_amd64.deb && \
> apt-get --fix-broken install -y
> ```
> 
> [ ! ] you need to launch google-chrome from the terminal cause google-chrome launcher isn't built in fluxbox menu.
> Launch google chrome by running the below command in the terminal:
> `google-chrome-stable --no-sandbox`
> If your issue is resolved then close this issue.

I'll try this, thanks for the fast answer. I'll close this, if I'm stuck I just reopen this issues later. 👍
