### ISSUE TITLE
adding rclone

### ISSUE THREAD

**Issue by armin-malek** [vital987/vubuntu#20]
hey, can you add rclone to the project?
it's really useful and I'm having troble editing your project so...

**Comment by vital987** [comment]
I cannot do that cause it's not a necessary tool, you need to DIY it. Just add your customizations on the top of vubuntu images by building the below Dockerfile:
```
#Change the image tag(latest) to whatever image you want.
FROM vital987/vubuntu:latest
RUN curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip && \
    unzip rclone-current-linux-amd64.zip -d /tmp && \
    cp /tmp/rclone-*-linux-amd64/rclone /usr/bin/ && \
    chown root:root /usr/bin/rclone && \
    chmod 755 /usr/bin/rclone && \
    rm -rf rclone* /tmp/*
```   
This will install rclone to the docker image but if you thinking about using rclone on heroku for mounting filesystems then it will not work cause Heroku dosen't allow FUSE. Also if you trying to run it on other systems, make sure they support FUSE (/dev/fuse). Close the issue **if your issue is solved**.

**Comment by Box-boi** [comment]
The `RUN....` Part Has To Be Included In Dockerfile.heroku Right?
I was Interested In Adding backup features, this way, App data like telegram, browser data(addons, etc), and Other app data Would be backed up To Gdrive(or a teamdrive), by keeping .cache .local/app .config .ssh .vscode and so on, as The server gets reset upon restarting heroku

**Comment by vital987** [comment]
Yup, but Heroku dosen't support FUSE filesystem.

**Comment by box-automation1** [comment]
> Yup, but Heroku dosen't support FUSE filesystem.

ooo, so rsync isn't possible, are you aware of any other lightweight backup solutions?

**Comment by vital987** [comment]
Use google drive upload API, I implemented that in my [code-server](https://github.com/vital987/code-server) wrapper but removed due to implementation issues, checkout previous commits of that projects.

**Comment by vital987** [comment]
Use google drive upload API, I implemented that in my [code-server](https://github.com/vital987/code-server) wrapper but removed due to implementation issues, checkout previous commits of that projects.

**Comment by Box-boi** [comment]
> Yup, but Heroku dosen't support FUSE filesystem.

My Goal is to create a persistent Environment, and in this case, i would not need FUSE support, as i won't be mounting the google-drive, instead, ill be doing something like this

`(1)`: When Heroku App Restarts: `rclone copy remote:telegram-data` && `rclone copy remote:.cache` && `rclone copy remote.vscode` and similar, Start Command Can Modified Via Procfile(iirc) and rclone.conf can be stored in a github-secret-gist, the link of which will be in heroku-environment-variable
`(2):` When App Has Started Already, Every `30 Minutes` Via Heroku-Job-Scheduler, the command `rclone sync ~/.cache remote:.cache` && `rclone sync ~/.vscode` ... same for all apps(Telegram, Libre-Office, Firefox, etc)

Thus, Data(& cache) would be back-ed(synced) up every 30min(or maybe 1hour) to google drive, and Would be re-copied to Their Respective Directories when the Heroku App Restarts

So Far Rclone Part Has Been Done, I'm Now Working on The cron-job part

**Comment by vital987** [comment]
Don't we need to mount cloud storage to the system for copying the files?

**Comment by Box-boi** [comment]
> Don't we need to mount cloud storage to the system for copying the files?

I maybe wrong, but can you check this screenrecording?

https://boxmirror.boxmirror.workers.dev/0:/simplescreenrecorder-2021-12-01_09.23.38.mp4?a=view

if this is just what one would need rclone for, then i guess FUSE isnt needed

**Comment by vital987** [comment]
Instead try using AWS Free tier, free EC2 instances for 12 months + lots of many services to take benefit of. You can run 1GB + 1vCPU + 8GB linux/windows instance continuesly for straight 12 months, EC2 is a VM so it has devices like FUSE, TUN, etc. + no need to save any cache as the storage isn't ephemeral.

**Comment by Box-boi** [comment]
> Instead try using AWS Free tier, free EC2 instances for 12 months + lots of many services to take benefit of. You can run 1GB + 1vCPU + 8GB linux/windows instance continuesly for straight 12 months, EC2 is a VM so it has devices like FUSE, TUN, etc. + no need to save any cache as the storage isn't ephemeral.

Oracle cloud gives lifetime free server under their always free tier, it's way better than AWS

They give two options 
(A) 1gb ram, 1 core x86 AMD cpu with 0.5gbps internet, free for lifetime
OR
(2) 24gb ram, 4 crore, ARM cpu with 6gbps internet, free for lifetime

These severs are far better than heroku, but are no fun, as they aren't a challenge to setup, and have ample resources, I was interested in this project because of its sheer efficiency and the ability to be creative with such limited resources

**Comment by vital987** [comment]
Oh yes, I forgot about Oracle, apologies for that, but if you just want to upload & retrieve cache to minimize the loss cause by restarting. One thing you can do is make a script that will compress all the cache into the zip file and then upload it somewhere and when the dyno start, download the zip file using wget/curl and re-place all the existing files back in place.

**Comment by Box-boi** [comment]
> Oh yes, I forgot about Oracle, apologies for that, but if you just want to upload & retrieve cache to minimize the loss cause by restarting. One thing you can do is make a script that will compress all the cache into the zip file and then upload it somewhere and when the dyno start, download the zip file using wget/curl and re-place all the existing files back in place.

yes, im planning to do just that, but instead of manually uploading and downloading, i will run it similar to `self-ping.py` like maybe every 3 hours, so it would upload to gdrive every 3 hours, and auto download upon heroku-app restarting

my curent config is: https://github.com/Box-boi/vubuntu/blob/master/assets/scripts/self-backup.py
and https://gist.github.com/Box-boi/dda8fe9a1be8c21b5666fd317a9d40cc (yet to add the zip feature)

**Comment by vital987** [comment]
Issue closed.
Reason: Stale
